name: VALOR Autonomy Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-log:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests

      - name: Update log
        run: |
          echo "🔁 AUTONOMY UPDATE $(date)" >> system_log.md
          echo "🧠 Render synced + GitHub action triggered." >> system_log.md

      - name: Commit and push log
        run: |
          git config --global user.name 'VALOR AI'
          git config --global user.email 'valor-autonomy@users.noreply.github.com'
          git add system_log.md
          git commit -m "📤 Update system log [auto]"
          git push
